version: 2
workflows:
  version: 2
  compile_and_lint:
    jobs:
      - compile
      - lint
jobs:
  compile:
    docker:
      - image: circleci/buildpack-deps:18.04
    steps:
      - checkout
      - run: sudo apt install -y portaudio19-dev autoconf-archive
      - run: autoreconf --install && ./configure && make
  lint:
    docker:
      - image: circleci/buildpack-deps:18.04
    steps:
      - checkout
      - run: sudo apt install -y python3 python3-pip
      - run: python3 -m pip install cpplint
      - run: python3 -m cpplint src/*.cpp

