version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: sudo apt install -y portaudio19-dev autoconf-archive
      - run: autoreconf --install && ./configure && make
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: sudo apt install -y python3 python3-pip
      - run: python3 -m pip install cpplint
      - run: cpplint src/*.cpp

